### ISSUE TITLE
Make output.html more readable

### ISSUE THREAD

**Issue by miri64** [kaspar030/murdock#6]
People seem to have huge problems reading the output.html (I myself sometimes need to look 2-3 times before finding the error). How about instead of returning one huge chunk of text returning something more structured as JSON that then can be parsed and displayed similar to how the PRs are displayed.

I'm thinking about something like this (using YAML instead of JSON so it's easier to read):

```yaml
pr_build:
  - build_group1:
      status: success
      output: ...
  - build_group2:
      status: failure
      output: ...
  - ...
```
